### ISSUE TITLE
twmnd abort (Core dumped)  after installating

### ISSUE THREAD

**Issue by moraisaugusto** [sboli/twmn#72]
I installed/compiled twmn via arch repo [twmn-git 182.1d9c9cc-1](https://aur.archlinux.org/twmn-git.git ) and directly from GH ([1d9c9cc](https://github.com/sboli/twmn/commit/1d9c9cc170f13712d13142c3f9dc13e76173d503)) but when I tried to run twmnd I got this msg:

`[1]    13086 abort (core dumped)  twmnd`

I backtraced it with gdb and got this:

```
Starting program: /home/augusto/.builds/twmn-git/twmn/bin/twmnd
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
Starting twmnd version 1.2
[New Thread 0x7fffeb5d0700 (LWP 21799)]

Thread 1 "twmnd" received signal SIGABRT, Aborted.
0x00007ffff4afe670 in raise () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ffff4afe670 in raise () at /usr/lib/libc.so.6
#1  0x00007ffff4affd00 in abort () at /usr/lib/libc.so.6
#2  0x00007ffff5c61807 in  () at /usr/lib/libQt5Core.so.5
#3  0x00007ffff5e7c7fe in QObjectPrivate::QObjectPrivate(int) () at /usr/lib/libQt5Core.so.5
#4  0x00007fffe9ca90ee in  () at /usr/lib/qt/plugins/styles/libqgtk2style.so
#5  0x00007fffe9c975ce in  () at /usr/lib/qt/plugins/styles/libqgtk2style.so
#6  0x00007fffe9cab99d in  () at /usr/lib/qt/plugins/styles/libqgtk2style.so
#7  0x00007ffff71fc3a3 in QStyleFactory::create(QString const&) () at /usr/lib/libQt5Widgets.so.5
#8  0x00007ffff7220f0c in QProxyStyle::QProxyStyle(QString const&) () at /usr/lib/libQt5Widgets.so.5
#9  0x00007fffe9eb9386 in Qt5CTProxyStyle::Qt5CTProxyStyle(QString const&) ()
    at /usr/lib/qt/plugins/styles/libqt5ct-style.so
#10 0x00007fffe9eb8fe0 in Qt5CTStylePlugin::create(QString const&) () at /usr/lib/qt/plugins/styles/libqt5ct-style.so
#11 0x00007ffff71fc3a3 in QStyleFactory::create(QString const&) () at /usr/lib/libQt5Widgets.so.5
#12 0x00007ffff7192eda in QApplication::style() () at /usr/lib/libQt5Widgets.so.5
#13 0x00007ffff719322d in QApplicationPrivate::initialize() () at /usr/lib/libQt5Widgets.so.5
#14 0x00007ffff7193284 in QApplicationPrivate::init() () at /usr/lib/libQt5Widgets.so.5
#15 0x000000000040980a in main(int, char**) (argc=1, argv=0x7fffffffdb78) at main.cpp:48
```
It seems be a missing QT lib. 

Some clue ?

**Comment by joekienzle** [comment]
I installed the latest version via arch:
```$ pacaur -Qs twmn
local/twmn-git 186.5b92ac5-1
    A notification system for tiling window managers```
Didn't have that issue. Do you still have it?
